// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rawygdmiabtagewqalmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhd3lnZG1pYWJ0YWdld3FhbG12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NDY4MDQsImV4cCI6MjA2ODEyMjgwNH0.JsDH4sgeyVOOYRqnCcrB0TP0WJVzD3ovqS3UlEiGKNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});